#pragma once

/**** FX data header generated by fxdata-build.py tool version 1.07 ****/

using uint24_t = __uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xffb2;
constexpr uint24_t FX_DATA_BYTES = 19968;

constexpr uint24_t LEVELS_DEFAULT = 0x000000;
constexpr uint24_t LEVELS_SIMPLE = 0x004900;
